# Generated by Django 5.2.7 on 2025-10-04 11:06

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('source_code_location', models.CharField(choices=[('in_app_module', 'In-App Module (Bundled)'), ('s3_artifact', 'S3 Bucket Artifact (Dynamic)')], default='s3_artifact', max_length=255)),
                ('source_code_path', models.CharField(max_length=100, null=True)),
                ('runtime', models.CharField(choices=[('subprocess', 'Subprocess'), ('container', 'Container')], default='subprocess', max_length=100)),
            ],
            options={
                'ordering': ('key', '-version'),
                'unique_together': {('key', 'version')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationAction',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('entrypoint_function', models.CharField(max_length=100)),
                ('input_schema', models.JSONField(default=None, null=True)),
                ('output_schema', models.JSONField(default=None, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='integrations.integration')),
            ],
            options={
                'unique_together': {('integration', 'key')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid_utils._uuid_utils.uuid7, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('entrypoint_function', models.CharField(max_length=100)),
                ('input_schema', models.JSONField(default=None, null=True)),
                ('output_schema', models.JSONField(default=None, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='integrations.integration')),
            ],
            options={
                'unique_together': {('integration', 'key')},
            },
        ),
    ]
